version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:17.2.0
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/dаta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
  minio:
    image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-qc
    environment:
      #Redis
      REDIS_HOST: "45.156.185.11"
      REDIS_PORT: 6379
      BULL_QUEUE: "analyseCalls"
      # General Configuration
      NODE_ENV: "test" # Options: 'development', 'production'
      PORT: "8081"
      HOST: "0.0.0.0" # Ensures the container is accessible externally

      # Database Configuration
      DATABASE_URL: "postgresql://myuser:mypassword@45.156.185.11:5433/mydb?schema=public"

      # CORS Configuration
      CORS_ORIGIN: "*"

      # Authentication
      JWT_SECRET: "hi"

      # Rate Limiting
      COMMON_RATE_LIMIT_WINDOW_MS: "1000"
      COMMON_RATE_LIMIT_MAX_REQUESTS: "20"

      # File Server
      FILE_SERVER_BASE_URL: "http://185.243.48.218:4567/"

      # MinIO Configuration
      MINIO_ENDPOINT: "minio"
      MINIO_ENDPOINT_UTL: "http://45.156.185.11:9000"
      MINIO_PORT: "9000"
      MINIO_ACCESS_KEY: "minioaccesskey"
      MINIO_SECRET_KEY: "miniosecretkey"
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - postgres
      - minio
    networks:
      - app-network
    volumes:
      - ./src/api/session/audio_files:/usr/src/app/dist/audio_files

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
